### ISSUE TITLE
Compact layout mode for power-users (less vertical whitespace)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#109]

**Comment by discordianfish** [comment]
Why power users? Is desktop usage now synonymous with power user? :)

But +1000, I love vector.im but the UI.. I find it really hard to follow the chat passively while working.

Maybe it's personal preference in which case I'd really like to see custom themes or something like that. Or maybe I'm not the only one feeling like the UI lacks some intuitive structure which I believe is mostly caused by too much whitespace.

If you compare it to slack for instance, vector shows less content while feeling more cluttered IMO.

**Comment by richvdh** [comment]
> Why power users? Is desktop usage now synonymous with power user? :)

We probably want to keep the clean view for new users, so a compact view would be optional.

Perhaps "experienced users" is a better term than "power users".

**Comment by juliusv** [comment]
When I think about "compact", I'm thinking about something that looks more like Slack - that's not for power users either.

But sure, an even more compact view (like e.g. irssi / weecht) would be interesting as well :)

**Comment by discordianfish** [comment]
Let me first say that the riot redesign improved the situation a lot already. So great job on this!

I personally would like if we could:
- reduce the (vertical) whitespaces a bit more
- increase font weight for text messages
- align top of avatar with top of nickname (and maybe think about using (rounded) squares like Slack)

Which, to be frank, makes it simply a bit more slack looking.. But I think they nailed the design.

**Comment by juliusv** [comment]
@discordianfish for parts of that, https://github.com/vector-im/vector-web/issues/2300 could be relevant

**Comment by Dasoren** [comment]
I would like to cast my vote in favor of this.

I would really like it if riot-web, had a lot less vertical white space.

**Comment by allanday** [comment]
I'm pretty sure that the current layout can be incrementally improved in order to make it a bit more space efficient and easy to read, while still keeping the existing look and feel. Here's a screenshot, which I've modified (original on the left, modified version on the right):

![riot-chat-spacing](https://cloud.githubusercontent.com/assets/213068/23667815/07d35eba-0357-11e7-93de-41d32fce5696.png)

Aligning avatar images with the top of names makes conversations easier to read in my opinion.

**Comment by discordianfish** [comment]
@allanday That looks great!

**Comment by juliusv** [comment]
I'm going even more compact (and higher contrast) with a local style:

![design](https://cloud.githubusercontent.com/assets/538008/23678364/233f5924-0384-11e7-839d-a8df3c2449a9.png)

via this CSS:

```css
body {
    color: #2c2d30;
}

.mx_EventTile {
    padding-top: 0;
}

.mx_EventTile .mx_SenderProfile {
    color: #2c2d30 !important;
    font-weight: bold;
    opacity: 1;
}

.mx_RoomTile_name {
    color: #2c2d30;
}

.mx_EventTile_line {
    padding-top: 1px;
    padding-bottom: 1px;
}

.mx_EventTile_avatar {
    top: 0;
}
```
