### ISSUE TITLE
Filter button doesn't use correct color

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12630]
The Explore button right next to it uses `timeline-text-secondary-color` for its text color but the Filter button text color is always white no matter what custom theme variables you use.

The Filter button should use `timeline-text-secondary-color` for its text color.

<img width="278" alt="Screen Shot 2020-03-05 at 7 09 43 PM" src="https://user-images.githubusercontent.com/5855073/76041010-adeb0000-5f16-11ea-8c46-06d5cefbc8f0.png">
<img width="212" alt="Screen Shot 2020-03-05 at 7 01 38 PM" src="https://user-images.githubusercontent.com/5855073/76041011-ae839680-5f16-11ea-8d0f-62c93d7a6d59.png">

**Comment by ThobyV** [comment]
Hello, I'm an aspiring GSOC 2020 candidate with experience building react  applications. May I be assigned to this issue?

**Comment by aaronraimist** [comment]
Sure you are welcome to work on it.

**Comment by Infinity-Intellect** [comment]
@aaronraimist Has this been fixed already ? Isn't it how it's supposed to be as in the picture below ? If there is another way to reproduce the issue, please let me know, I would also like have a go at this issue.

![textColor](https://user-images.githubusercontent.com/49329642/76168080-f7934f00-6191-11ea-8d05-7c696a00437a.PNG)

**Comment by aaronraimist** [comment]
No it is not fixed. You have to be using a custom theme to be able to notice it.

For example it is easy to notice using this theme: https://raw.githubusercontent.com/aaronraimist/riot-web-themes/master/Geeko%20Dark/Geeko%20Dark.json

You can install custom themes with https://github.com/matrix-org/matrix-react-sdk/pull/4148

**Comment by aaronraimist** [comment]
The file you'll probably want to edit to fix this is https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/light-custom/css/_custom.scss

**Comment by ThobyV** [comment]
Ok thank you @aaronraimist I am working on it I am hoping to send PR as soon as possible. I will be sure to comment on this thread for guidelines.

**Comment by Infinity-Intellect** [comment]
@aaronraimist The custom theme  URL text box is not getting enabled for me. How to get it enabled? I'm not able to get it from the link you mentioned above to 'install custom themes'.

**Comment by fooness** [comment]
I fear this cannot be fixed in `matrix-react-sdk/blob/develop/res/themes/light-custom/css/_custom.scss` …

The search box has no color properties assigned in the first place, so this needs to be added in, I guess, `matrix-react-sdk/res/css/structures/_SearchBox.scss` first and then the scss variables would need to be assigned css variables in `matrix-react-sdk/blob/develop/res/themes/light-custom/css/_custom.scss` …

Also, I guess, some hover properties would need to be defined, like for example also for the explore button in https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/structures/_LeftPanel.scss#L159-L161 … the scss variable used here (for both elements), in my opionion, should NOT be `$primary-bg-color` but rather something new like `$button-highlight-color` or something existing like `$accent-color` … because there’s people who don’t want the side bar to have a different background than the timeline.

**Comment by fooness** [comment]
In `matrix-react-sdk/res/css/structures/_SearchBox.scss`, add `color: $notice-secondary-color;` at two positions.

```
.mx_SearchBox {
    color: $notice-secondary-color;
    flex: 1 1 0;
    min-width: 0;

    &.mx_SearchBox_blurred:not(:hover) {
        background-color: transparent;
    }

    .mx_SearchBox_closeButton {
        color: $notice-secondary-color;
        cursor: pointer;
        background-image: url('$(res)/img/icons-close.svg');
        background-repeat: no-repeat;
        width: 16px;
        height: 16px;
        background-position: center;
        padding: 9px;
    }
}
```

 The same can already be found for the explore button/icon in `matrix-react-sdk/res/css/structures/_LeftPanel.scss` …

This does not, yet, fix the color of the search ICON. Not sure where this icon is defined …

**Comment by fooness** [comment]
Same applies to `Filter room members` in member list, this also does not respect the color definitions. Probably to be solved the same way as the other filter button/input …

<img width="208" alt="Screenshot 2020-04-12 at 01 34 28" src="https://user-images.githubusercontent.com/11408027/79057130-e8566400-7c5d-11ea-9590-f5ee0f04922b.png">

**Comment by fooness** [comment]
Unfortunately I don’t quite figure out how to solve this. **_Help wanted and needed._** Thank you!

**Comment by t3chguy** [comment]
Currently it uses the svg as a background image, it'd need to be changed into using an svg css mask if you want its colour to be changeable in css.

**Comment by fooness** [comment]
Hm, not sure on how to correctly convert this. I tried, in `res/css/_common.css`:

```scss
input[type=text].mx_textinput_icon,
input[type=search].mx_textinput_icon {
    padding-left: 36px;
    //background-repeat: no-repeat;
    //background-position: 10px center;
    //color: $notice-secondary-color;
    mask: url('$(res)/img/feather-customised/search-input.svg');
    mask-repeat: no-repeat;
    mask-position: 10px center;
    background-color: $notice-secondary-color;
}

// FIXME THEME - Tint by CSS rather than referencing a duplicate asset
input[type=text].mx_textinput_icon.mx_textinput_search,
input[type=search].mx_textinput_icon.mx_textinput_search {
    //background-image: url('$(res)/img/feather-customised/search-input.svg');
    //background-color: $notice-secondary-color;
    color: $notice-secondary-color;
}
```

But that results in the placeholder/input text not being seen:

<img width="359" alt="Screenshot 2020-04-12 at 15 16 45" src="https://user-images.githubusercontent.com/11408027/79069717-b205fc80-7cd0-11ea-849d-023b1e93037d.png">
