### ISSUE TITLE
How can I set up encrypted recovery when I use SAML SSO login?

### ISSUE THREAD

**Issue by hungrymonkey** [vector-im/riot-web#13580]
<img width="1571" alt="Screen Shot 2020-05-07 at 8 32 57 AM" src="https://user-images.githubusercontent.com/771339/81314248-befedd00-903d-11ea-8d01-8b91198b9c12.png">

### Description

I have a self-hosted matrix synapse service with this configuration below.
https://edenmal.moe/post/2019/Matrix-Synapse-SAML2-Login/#your-matrix-synapse-homeserver-config-yaml-file
https://github.com/spantaleev/matrix-docker-ansible-deploy
```
matrix_synapse_configuration_extension_yaml: |
  saml2_config:
    enabled: true
    config_path: "/data/sp_conf.py"
    idp_redirect_url: "https://keycloak.domain.tld:8443/auth/realms/master/protocol/saml"
```

How can I enter my password when I use SSO login?
### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

1. Set up self-hosted service with SAML IDP
2. Login
3. Attempt to set up recovery password

Describe how what happens differs from what you expected.

I should be able to redirect to my login server.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Any
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Any
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web? Riot Web 1.6.0

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.6.0
