### ISSUE TITLE
Make middlepanel width optionally customisable

### ISSUE THREAD

**Issue by matrixbot** [vector-im/riot-web#1371]
Created by @ matthew:matrix.org.

**Comment by sbts** [comment]
This is a regression.
The message pane no-longer expands when the window width is increased.
This is both annoying and a waste of space.
The problem occurs on both app and develop and is a regression as it used to expand just fine.
see [Riot-need-to-expand-message-pane.png](https://matrix.org/_matrix/media/v1/download/matrix.org/NCxuQfhxUBxncgaqWcREIwwj) for an example screenshot"

**Comment by MTRNord** [comment]
For Browser user I have this:
Either use this UserStyle: https://userstyles.org/styles/144258/riot-im-wide
Or this Userscript: https://userstyles.org/styles/userjs/144258/riot-im-wide.user.js
Or go with this css code (needs to be added after the build)
```css
@-moz-document url-prefix("https://riot.im/app/"), url-prefix("https://riot.im/develop/"), url-prefix("https://riot.im/beta/"), url-prefix("https://riot.im/staging/")
{
  .mx_RoomView_messageListWrapper
  {
    max-width: 100% !important;
  }

  .mx_MessageComposer_wrapper
  {
    max-width: 100% !important;
  }

  .mx_RoomHeader .mx_RoomHeader_wrapper
  {
    max-width: 100% !important;
  }

  .mx_RoomView .mx_RoomView_auxPanel
  {
    max-width: 100% !important;
    max-height: 74% !important;
  }

  .mx_UserSettings
  {
    max-width: 100% !important;
  }

  .mx_TopUnreadMessagesBar
  {
    max-width: 100% !important;
  }

  .mx_RoomDirectory
  {
    max-width: 87% !important;
  }

  .mx_HomePage
  {
    max-width: 87% !important;
  }

  .mx_HomePage_header
  {
    max-width: 78% !important;
  }

  .mx_Dialog
  {
    max-width: 100% !important;
    border-radius: 5px !important;
  }

  .mx_UserSettings_toggle
  {
    margin-bottom: 6px !important;
  }

  .mx_UserSettings_advanced
  {
    line-height: 183% !important;
  }

  .mx_UserNotifSettings_pushRulesTable
  {
    line-height: 172% !important;
  }

  .mx_RoomView_statusAreaBox
  {
    max-width: 100% !important;
  }
}
```
