### ISSUE TITLE
there's a bad pop when sticky headers de-sticky on the new room list

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14429]
It looks we're failing to leave a gap in the roomsublist for the header when the header is stickied, so as the header switches between sticky/non-sticky the size of the sublist pops badly.  Given the sticky transition lags scrolling, this is very noticeable.

There's a video of this happening in the [internal room](https://matrix.to/#/!NTUKVQdPRwdQhaunBn:matrix.org/$BQRniy0pmgLQBdnXI0v9_En6kP8A0HhKCOldDRFpYhs?via=matrix.org&via=t2l.io&via=kaplu.mba).

The solution is probably to add padding to the roomsublist and negative top margin to the header when non-sticky so that the header can be absolute-positioned without making the roomsublist layout change.

This is how I did it in the PoC at https://jsfiddle.net/afy3unq4/17/:

```css
.roomSublist {
    /* leave room at the top for the sublist header */
    padding-top: 48px;
}

.roomSublistHeader {
    font-weight: bold;
    height: 48px;
    /* inset into the sublist header top, so we can
       switch it between absolute & relative position as needed */
    margin-top: -48px;
}
```
