### ISSUE TITLE
use tabular numbers in timestamps

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#14686]
Since we default to a font that has fancy OpenType features, we should add

```css
.mx_MessageTimestamp {
  font-variant-numeric: tabular-nums;
}
```

so that timestamps are aligned.

Before (with always-show-timestamps and IRC layout):
![image](https://user-images.githubusercontent.com/1012976/88109985-6c7f8800-cb79-11ea-9d79-183be8f29bcf.png)

After:
![image](https://user-images.githubusercontent.com/1012976/88110067-8b7e1a00-cb79-11ea-94ef-f6d0bdff0832.png)
