### ISSUE TITLE
Custom tag panel tiles in the community filter panel get vertically padded twice

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#14705]
### Description

AccessibleButton adds 10px of padding above and 9px below, and the tiles in the custom tag panel nest an AccessibleButton inside of another AccessibleButton, resulting in a total of 20px of padding above and 18 below.

### Steps to reproduce

1. Have custom tags
2. Enable the community filter panel

This results in something like this:

![image](https://user-images.githubusercontent.com/99404/88212830-bbc2c880-cc0c-11ea-9655-7db38d8c41ba.png)

When I would have expected something more like this:

![image](https://user-images.githubusercontent.com/99404/88212966-ef9dee00-cc0c-11ea-8791-a8cd2ef0fefb.png)

I used a userstyle to produce the latter; the CSS was:

```css
    /* The custom tags are spaced out absurdly far apart in the community filter panel */
    section#matrixchat .mx_LeftPanel .mx_CustomRoomTagPanel div.mx_AccessibleButton {
        padding-top: 0 !important;
        padding-bottom: 0 !important;
    }

    /* Having removed the double-padding, set the single-padding to something reasonable */
    section#matrixchat .mx_LeftPanel .mx_CustomRoomTagPanel span.mx_AccessibleButton.mx_BaseAvatar {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    /* Re-align the selection markers */
    section#matrixchat .mx_LeftPanel .mx_CustomRoomTagPanel .mx_AccessibleButton.CustomRoomTagPanel_tileSelected::before {
        top: 2px !important;
        height: 46px !important;
    }
```

### Version information

- **Platform**: web
- **Browser**: Firefox 75.0
- **OS**: Exherbo Linux
- **URL**: https://develop.element.io

(by the way, this template needs updated for the Riot -> Element change)
