### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by gwicke** [vector-im/riot-web#1635]
It would be great if there was an option to use a dark theme.

Here is a very minimal set of CSS tweaks as a start:

``` css
body {
    -webkit-filter: invert(100%);
    filter: invert(100%);
}
/* Do not invert avatar images:
  invert(invert()) = not inverted */

.mx_BaseAvatar_image {
    -webkit-filter: invert(100%) !important;
    filter: invert(100%) !important;
    background: white;
}
/* Ensure the right panel has a defined background, too */

.mx_RightPanel {
    background: white;
}
/* Increase text contrast */

.mx_SenderProfile {
    color: #060606 !important;
}
.mx_MessageComposer_input textarea,
.mx_EventTile {
    color: black;
}
```

Combined with #1633, this looks like this:

![image](https://cloud.githubusercontent.com/assets/1225898/16022615/9173ec46-316d-11e6-9fc4-93598972490d.png)
