### ISSUE TITLE
Option to hide lock icon in E2E channel

### ISSUE THREAD

**Issue by youcha33** [vector-im/riot-web#2882]
and make it visible with a hover on the message.

**Comment by ara4n** [comment]
we'll look at how to make the UX less noisy for E2E once it's out of beta.  Right now those icons are pretty critical.

**Comment by hedning** [comment]
For people wanting this behavior now (including show on hover): just add this css locally (eg. with Stylish):
```css
.mx_EventTile_e2eIcon {
   display: none;
}
```
