### ISSUE TITLE
MD in emotes causes a spurious linebreak after the displayname

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6090]

**Comment by lampholder** [comment]
What markdown specifically causes this?

I found multiline code blocks got squashed to a single line, and lots of other MD got ignored (#, +, *), but couldn't trigger a spurious newline failure mode.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/35868002-920d869a-0b18-11e8-964a-db6d14263bd3.png)

**Comment by uhoreg** [comment]
Can be fixed with something like this CSS:

```css
.mx_MEmoteBody .mx_EventTile_body.markdown-body>p:first-child {
    display: inline;
}
```
