### ISSUE TITLE
Phone number input should not be shown if homeserver does not support it

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#9063]
### Description

When creating an account for a homeserver that does not support phone based registration, the phone input is shown.

![selection_068](https://user-images.githubusercontent.com/1174866/53885190-c7b4e700-4025-11e9-834f-4201c400888f.png)

Filling a phone number and submitting brings an error which seems like could be avoided by exposing the capabilities of the homeserver and checking them as it is known at this stage.

![selection_069](https://user-images.githubusercontent.com/1174866/53885240-e5824c00-4025-11e9-9f7c-72217af32541.png)

Similarly, once signed up, the phone number input is visible in settings:

![selection_070](https://user-images.githubusercontent.com/1174866/53885318-12cefa00-4026-11e9-8864-73d996f28ecd.png)

Our enthusiastic user is presented with disappointment:

![selection_071](https://user-images.githubusercontent.com/1174866/53885331-1c586200-4026-11e9-8beb-952a3a5c08b6.png)

### Version information

Custom hosted Riot web v1.0.1 pointed to custom hosted Synapse v0.99.2.

**Comment by jryans** [comment]
Hmm, can you share the relevant Synapse config for this HS?

The phone input on registration should already be hidden after https://github.com/matrix-org/matrix-react-sdk/pull/2551, which is included in v1.0.0 and later.

**Comment by jaywink** [comment]
@jryans sorry for the slow reply :P Would you be able to say which parts are relevant for the Synapse config?

What I can see is that Riot is doing a `/register` to client API when rendering the form which goes something like this:

```
https://federator-staging.modular.im/_matrix/client/r0/register
{"auth":{}}

Response:

HTTP/1.1 401 Unauthorized
Server: Synapse/0.99.2.post1
```

The response contains the following flows:

```
"flows": [
    {
      "stages": [
        "m.login.email.identity",
        "m.login.recaptcha",
        "m.login.terms"
      ]
    },
    {
      "stages": [
        "m.login.msisdn",
        "m.login.email.identity",
        "m.login.recaptcha",
        "m.login.terms"
      ]
    }
  ],
```

Synapse config for what I can think might be relevant:

```
registrations_require_3pid: 
  - email
allowed_local_3pids: 
  - medium: email
    pattern: .*@jasonrobinson\.me$
allow_guest_access: False
register_mxid_from_3pid: email
disable_3pid_changes: False
disable_set_displayname: False
disable_set_avatar_url: False
```
